"""Stable column order for exported tables, including empty optional tables.

These names are part of the output interface. Defining them separately keeps
file-format maintenance independent from data extraction and plotting.
"""

TABLE_FIELDS: dict[str, list[str]] = {
    "vic_cells.csv": [
        "vic_position",
        "vic_id",
        "vic_row",
        "vic_col",
        "vic_area_m2",
        "vic_lat",
        "vic_lon",
        "vic_interface_elevation_m",
    ],
    "vic_mapping_summary.csv": [
        "vic_id",
        "vic_row",
        "vic_col",
        "vic_area_m2",
        "vic_lat",
        "vic_lon",
        "overlap_count",
        "coupled_area_m2",
        "coverage_fraction",
        "mf6_models",
        "mf6_nodes",
    ],
    "mf6_mapping_summary.csv": [
        "mf6_model",
        "mf6_node",
        "mf6_area_m2",
        "overlap_count",
        "coupled_area_m2",
        "coverage_fraction",
        "vic_cells",
    ],
    "mapping_summary.csv": ["metric", "value", "units"],
    "vic_exchange_daily.csv": [
        "step",
        "start",
        "end",
        "duration_days",
        "positive_m3",
        "negative_m3",
        "net_m3",
        "net_rate_m3_day",
        "maximum_water_error_mm",
        "source_files",
    ],
    "vic_exchange_cells.csv": [
        "step",
        "start",
        "end",
        "vic_position",
        "vic_id",
        "vic_row",
        "vic_col",
        "vic_lat",
        "vic_lon",
        "vic_area_m2",
        "exchange_mm",
        "exchange_volume_m3",
        "direction",
    ],
    "mf6_heads.csv": [
        "model",
        "time_days",
        "node",
        "head_m",
        "head_change_from_initial_m",
    ],
    "mf6_head_summary.csv": [
        "model",
        "time_days",
        "head_min_m",
        "head_mean_m",
        "head_max_m",
        "head_range_m",
    ],
    "mf6_cells.csv": [
        "model",
        "node",
        "area_m2",
        "top_m",
        "bottom_m",
        "x",
        "y",
        "row",
        "col",
        "initial_head_m",
        "final_head_m",
        "head_change_m",
        "geometry_source",
    ],
    "node_boundary_daily.csv": [
        "step",
        "start",
        "end",
        "model",
        "node",
        "target_volume_m3",
        "target_rate_m3_day",
        "applied_volume_m3",
        "applied_error_m3",
        "direction",
    ],
    "mf6_budget_terms.csv": [
        "model",
        "time_days",
        "dt_days",
        "term",
        "positive_rate_m3_day",
        "negative_rate_m3_day",
        "net_rate_m3_day",
        "positive_volume_m3",
        "negative_volume_m3",
        "net_volume_m3",
    ],
    "mf6_lateral_cells.csv": [
        "model",
        "time_days",
        "dt_days",
        "node",
        "flowja_row_net_rate_m3_day",
        "flowja_row_net_volume_m3",
    ],
    "mf6_lateral_pairs.csv": [
        "model",
        "time_days",
        "dt_days",
        "node_i",
        "node_j",
        "q_i_to_j_record_m3_day",
        "q_j_to_i_record_m3_day",
        "antisymmetry_error_m3_day",
        "pair_magnitude_m3_day",
        "pair_volume_m3",
    ],
    "mf6_cell_budget.csv": [
        "step",
        "start",
        "end",
        "model",
        "node",
        "head_before_m",
        "head_after_m",
        "storage_change_m3",
        "interface_volume_m3",
        "lateral_row_volume_m3",
        "expected_storage_change_m3",
        "cell_budget_residual_m3",
    ],
    "mf6_mass_balance.csv": [
        "model",
        "api_volume_m3",
        "storage_budget_volume_m3",
        "storage_state_change_m3",
        "other_nonstorage_volume_m3",
        "cbc_budget_residual_m3",
        "storage_terms",
        "other_nonstorage_terms",
        "complete",
        "reason",
    ],
}
